import { jsPDF } from "jspdf";
import type { PaymentClaim, Submission } from "../types";

export function generateStoriesReportPDF(claim: PaymentClaim) {
  const doc = new jsPDF();

  // Color Palette Constants
  const NAVY = [26, 62, 111];    // #1A3E6F
  const GOLD = [200, 151, 43];   // #C8972B
  const TEAL = [15, 110, 86];    // #0F6E56
  const OFFWHITE = [247, 247, 247]; // #F7F7F7
  const DARK = [30, 41, 59];

  // Header Banner (Navy #1A3E6F)
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.rect(0, 0, 210, 36, "F");

  // Gold Accent Line
  doc.setFillColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.rect(0, 36, 210, 3, "F");

  // Header Text
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("KBC BYLINE — STORIES REPORT", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Official Payment Claim Request | Kenya Broadcasting Corporation", 14, 26);

  doc.setFontSize(9);
  doc.text(`Ref: ${claim.id} | Month: ${claim.month}`, 140, 26);

  // Correspondent Information Block
  let y = 48;
  doc.setTextColor(DARK[0], DARK[1], DARK[2]);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Correspondent Information", 14, y);

  y += 6;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Name: ${claim.correspondentName}`, 14, y);
  doc.text(`Email: ${claim.correspondentEmail}`, 110, y);

  y += 5;
  doc.text(`Phone: ${claim.correspondentPhone}`, 14, y);
  doc.text(`Bank Details: ${claim.bankDetails}`, 110, y);

  y += 5;
  doc.text(`Status: ${claim.status.toUpperCase()}`, 14, y);
  doc.text(`Generated Date: ${new Date(claim.createdAt).toLocaleDateString()}`, 110, y);

  y += 10;
  // Section Header (Navy #1A3E6F)
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.rect(14, y, 182, 8, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Approved Filings & Platform Rate Breakdown", 18, y + 5.5);

  y += 12;

  // Table Headers
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setTextColor(DARK[0], DARK[1], DARK[2]);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Assignment Title / Filing", 16, y);
  doc.text("Platforms Aired", 115, y);
  doc.text("Verified", 155, y);
  doc.text("Rate (KES)", 182, y);

  y += 2;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, 196, y);
  y += 4;

  let totalCalculated = 0;

  // Submissions Rows with Alternating Off-White #F7F7F7
  claim.submissions.forEach((sub: Submission, index: number) => {
    const isEven = index % 2 === 0;
    if (isEven) {
      doc.setFillColor(OFFWHITE[0], OFFWHITE[1], OFFWHITE[2]);
      doc.rect(14, y - 4, 182, 12, "F");
    }

    doc.setTextColor(DARK[0], DARK[1], DARK[2]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);

    // Truncate long titles
    const titleText = sub.assignmentTitle.length > 50 ? sub.assignmentTitle.substring(0, 47) + "..." : sub.assignmentTitle;
    doc.text(titleText, 16, y);

    doc.setFont("helvetica", "normal");
    const platformsFormatted = sub.publishedPlatforms.map((p) => p.replace("_", " ").toUpperCase()).join(", ") || "TV/Radio";
    doc.text(platformsFormatted.substring(0, 25), 115, y);

    // Proof confirmed tag in Teal
    if (sub.proofConfirmed) {
      doc.setTextColor(TEAL[0], TEAL[1], TEAL[2]);
      doc.setFont("helvetica", "bold");
      doc.text("VERIFIED", 155, y);
    } else {
      doc.setTextColor(200, 0, 0);
      doc.text("PENDING", 155, y);
    }

    doc.setTextColor(DARK[0], DARK[1], DARK[2]);
    doc.setFont("helvetica", "bold");
    const amountStr = `KES ${sub.calculatedAmountKES.toLocaleString()}`;
    doc.text(amountStr, 196 - doc.getTextWidth(amountStr), y);

    totalCalculated += sub.calculatedAmountKES;
    y += 12;

    if (y > 260) {
      doc.addPage();
      y = 20;
    }
  });

  y += 4;
  doc.setDrawColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.setLineWidth(0.8);
  doc.line(14, y, 196, y);

  y += 8;

  // Total Payment Box in Gold #C8972B
  doc.setFillColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.rect(110, y, 86, 18, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("TOTAL AMOUNT DUE:", 114, y + 7);

  doc.setFontSize(14);
  const grandTotalStr = `KES ${claim.totalAmountKES.toLocaleString()}`;
  doc.text(grandTotalStr, 192 - doc.getTextWidth(grandTotalStr), y + 13);

  // Footer notes & signatures
  y += 30;
  doc.setTextColor(DARK[0], DARK[1], DARK[2]);
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("This Stories Report is auto-generated by KBC Byline Contributor Portal. Attach this PDF to your claim lodged with Finance.", 14, y);

  y += 15;
  doc.setFont("helvetica", "bold");
  doc.text("Correspondent Signature: _______________________", 14, y);
  doc.text("Managing Editor Sign-off: _______________________", 110, y);

  // Save the PDF
  doc.save(`KBC_Byline_StoriesReport_${claim.month.replace(" ", "_")}_${claim.correspondentName.replace(" ", "_")}.pdf`);
}
